# Travis CI configuration
language: java

jdk:
- oraclejdk8

before_install:
- wget "https://github.com/Pravian/Aero/archive/master.zip" -O aero.zip
- unzip aero.zip -d .
- cd Aero-master
- mvn install
- cd ..

# get us on the new container based builds, we're not using any fancyness
sudo: false

notifications:
  email: false
