name: Goldiriath
version: 0.0.1
main: net.goldiriath.plugin.Goldiriath
depend: [Citizens, ProtocolLib]
authors: [Prozza, derpfacedirk]
commands:
    goldiriath:
        usage: /<command> [reload]
        description: Shows information about the Goldiriath plugin.
        aliases: [go]
    gmobspawn:
        usage: /<command> dev <on | off>
        description: Manages mobspawns.
        aliases: [gmob]
    goption:
        usage: /<command> <dialoghandler> <optionset> <choice>
        description: Selects the option for use.
        aliases: [gopt]
    gdev:
        usage: /<command> <values...>
        description: Goldiriath development command.
        aliases: [gd]
    gitemmeta:
        usage: /<command> <info | create | delete | set <lore | name | level | tier> <value>>
        description: Shows information about or creates the item meta for an item.
        aliases: [gim]
    gitem:
        usage: /<command> <list | get <itemid>>
        description: Manages custom item storage.
        aliases: [gi]
    glog:
        usage: /<command> <list | add | remove>
        description: Manages player logging.
        aliases: [gl]
    gshop:
        usage: /<command> <shopprofile> <info | open>
        description: Open a shop
        aliases: [gs]
