name: Goldiriath
version: 0.0.1
main: net.goldiriath.plugin.Goldiriath
depend: [Citizens]
commands:
    goldiriath:
        usage: /<command> [reload]
        aliases: [go]
        description: Shows information about the Goldiriath plugin.
    mobspawn:
        usage: /<command> dev <on | off>
        description: Manages mobspawns.
        aliases: [ms,mobmanage]
    resetquest:
        usage: /<command> <player>
        description: Resets all quest progress.
    option:
        usage: /<command> <dialoghandler> <optionset> <choice>
        description: Selects the option for use.
    gdev:
        usage: /<command> <values...>
        description: Goldiriath development command
        aliases: [gd]
    gitemmeta:
        usage: /<command>
        description: Shows information about the item meta on an item.
        aliases: [gim]
    gitem:
        usage: /<command> <itemid>
        description: Obtains an item from the custom item storage.
        aliases: [gi]
