
hellzombie:
    name: '&4Zombie of Hell'
    type: ZOMBIE
    level: 5
    spawn_threshold: 600
    loot_profile: 
    item: IRON_SWORD:5
    helmet: LEATHER_HELMET:3
    chestplate: DIAMOND_CHESTPLATE:2
    leggings: GOLD_LEGGINGS
    boots: IRON_BOOTS:15
    potions:
        SPEED:
            duration: -1
            amplifier: 1
            ambient: true