name: GoldiriathPlugin
version: 1.2
main: me.dirkjan.goldiriath.Goldiriath
commands:
    resetquest:
        usage: /<command> <player>
        description: resets all quest progress
    newmobspawn:
        usage: /<command> <name> <type> <lvl>
        description: sets a new mobspawn
    removemobspawn:
        usage: /<command> <name>
        description: removes a mobspawn